### ISSUE TITLE
Observing requests/responses and passing them on?

### ISSUE THREAD

**Issue by nylen** [moll/node-mitm#5]
Normally if node-mitm observes a request, then it is not passed on to the server (as you would expect).

I'd like to observe the request, send it to the server, and observe the response as it comes back, but I'm having a hard time figuring out what to put in the `'request'` event handler to make this work.  Is this possible?

**Comment by moll** [comment]
Given that to get decent coverage you'd have to ensure every branch, conditional, boundary and statement gets executed, and preferably, do so in separate test cases. Lugging around huge responses for otherwise tiny tests is cumbersome, especially for the code reviewer. There's no reason either to include irrelevant response properties whose handling gets exercised in another test. I'd say white-list approach (select only the properties absolutely necessary) is simpler than trying to pare things down.

If the endpoint's API is unclear or unspecified, then that's a wholly different problem and probably better solved by manual exploratory coding.
